# Traefik Configuration for Production
# This file configures Traefik with Let's Encrypt SSL certificates via Cloudflare

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Certificate resolvers
certificatesResolvers:
  cloudflare:
    acme:
      email: admin@quizzby.com
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 30s

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: quizzby-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

# API and dashboard
api:
  dashboard: true
  debug: false

# Logs
log:
  level: INFO
  format: json

accessLog:
  format: json

# Metrics (optional)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true