version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: quizzby-portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    environment:
      - PORTAINER_HTTP_DISABLED=false
    command: >
      --admin-password-file=/data/admin_password
      --hide-label=com.docker.compose.project
      --hide-label=com.docker.compose.service
    networks:
      - quizzby-network
    labels:
      - "com.quizzby.service=portainer"
      - "com.quizzby.environment=production"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Portainer Agent for remote Docker management (optional)
  portainer-agent:
    image: portainer/agent:latest
    container_name: quizzby-portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    networks:
      - quizzby-network
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer-agent
    labels:
      - "com.quizzby.service=portainer-agent"
      - "com.quizzby.environment=production"
    profiles:
      - agent

volumes:
  portainer-data:
    driver: local

networks:
  quizzby-network:
    external: true