version: '3.8'

services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: quizzby-nocodb
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NC_DB=pg://postgres:5432?u=nocodb&p=${NOCODB_DB_PASSWORD:-nocodb123}&d=nocodb
      - NC_AUTH_JWT_SECRET=${NOCODB_JWT_SECRET:-your-jwt-secret-key}
      - NC_PUBLIC_URL=${NOCODB_PUBLIC_URL:-http://localhost:8080}
      - NC_ADMIN_EMAIL=${NOCODB_ADMIN_EMAIL:-admin@quizzby.com}
      - NC_ADMIN_PASSWORD=${NOCODB_ADMIN_PASSWORD:-admin123}
      - NC_DISABLE_TELE=true
      - NC_TOOL_DIR=/usr/app/data/
    volumes:
      - nocodb-data:/usr/app/data
    depends_on:
      - postgres
    networks:
      - quizzby-network
    labels:
      - "com.quizzby.service=nocodb"
      - "com.quizzby.environment=production"

  postgres:
    image: postgres:15-alpine
    container_name: quizzby-nocodb-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nocodb
      - POSTGRES_USER=nocodb
      - POSTGRES_PASSWORD=${NOCODB_DB_PASSWORD:-nocodb123}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - quizzby-network
    labels:
      - "com.quizzby.service=nocodb-database"
      - "com.quizzby.environment=production"

volumes:
  nocodb-data:
    driver: local
  postgres-data:
    driver: local

networks:
  quizzby-network:
    external: true